server:
  port: 10010 # 网关端口，指定网关服务监听的端口号

spring:
  application:
    name: gateway # 服务名称，指定网关服务在 Spring 应用中的名称

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.1:80/nacos # Nacos 服务地址，指定 Nacos 注册中心的地址，通过 Nginx 代理访问

    gateway:
      routes: # 网关路由配置，用于定义各种路由规则
        - id: user-service # 路由ID，自定义的唯一标识符
          # uri: http://127.0.0.1:8081 # 静态路由目标地址，用于将请求转发到指定的地址
          uri: lb://user-service # 动态路由目标地址，使用负载均衡，将请求转发到名为 'user-service' 的服务实例
          predicates: # 路由断言条件，决定请求是否匹配该路由规则
            - Path=/user/** # 路径断言，只要请求路径以 /user/ 开头，就匹配该路由规则
          filters:
            - AddRequestHeader=Header, Camellia·XIAOHUA # 请求过滤器，添加一个请求头

        - id: order-service # 路由ID，自定义的唯一标识符
          uri: lb://order-service # 动态路由目标地址，使用负载均衡，将请求转发到名为 'order-service' 的服务实例
          predicates: # 路由断言条件，决定请求是否匹配该路由规则
            - Path=/order/** # 路径断言，只要请求路径以 /order/ 开头，就匹配该路由规则
            - Before=2030-01-20T17:42:47.789-07:00[Asia/Shanghai] # 时间断言，只在指定时间之前匹配
      default-filters: # 默认过滤项，应用于所有路由
        - AddRequestHeader=Header, Global filters! # 请求过滤器，添加一个全局请求头

logging:
  level:
    org.springframework.cloud.gateway: DEBUG # 设置 Spring Cloud Gateway 的日志级别为 DEBUG，用于调试
    org.springframework.web: DEBUG # 设置 Spring Web 的日志级别为 DEBUG，用于调试
